create table NF (Tables varchar(255), Form varchar(255), Y_N varchar(255),Reason varchar(255), PRIMARY KEY (Tables));
insert into NF (Tables,Form) VALUES ('TestR', '3NF');
insert into NF (Tables,Form) VALUES ('TestR', 'BCNF');
select count(*) from (select distinct K1,K2 from TestR) as AA;
select count(*) from TestR;
select count(*) from TestR where K1 IS NULL;
select count(*) from TestR where K2 IS NULL;
select count(*) from (select K1 from TestR group by K1) as T1;
select count(*) from (select K1,A from TestR group by K1,A) as T2;
select count(*) from (select K1,B from TestR group by K1,B) as T2;
update NF set Y_N = 'N', Reason = 'not 2nf, K1->B' WHERE Tables = 'TestR' and Form = '3NF'
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'TestR' and Form = 'BCNF'
insert into NF (Tables,Form) VALUES ('TestS', '3NF');
insert into NF (Tables,Form) VALUES ('TestS', 'BCNF');
select count(*) from (select distinct K1 from TestS) as AA;
select count(*) from TestS;
select count(*) from TestS where K1 IS NULL;
insert into NF (Tables,Form) VALUES ('TestT', '3NF');
insert into NF (Tables,Form) VALUES ('TestT', 'BCNF');
select count(*) from (select distinct K1,K2 from TestT) as AA;
select count(*) from TestT;
select count(*) from TestT where K1 IS NULL;
select count(*) from TestT where K2 IS NULL;
select count(*) from (select K1 from TestT group by K1) as T1;
select count(*) from (select K1,A from TestT group by K1,A) as T2;
select count(*) from (select K2 from TestT group by K2) as T1;
select count(*) from (select K2,A from TestT group by K2,A) as T2;
select count(*) from (select A from TestT group by A) as T1;
select count(*) from (select A from TestT group by A) as T1;
select count(*) from (select A,K1 from TestT group by A,K1) as T2;
select count(*) from (select A,K2 from TestT group by A,K2) as T2;
update NF set Y_N = 'Y', Reason = '' WHERE Tables = 'TestT' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'A->K2' WHERE Tables = 'TestT' and Form = 'BCNF';
insert into NF (Tables,Form) VALUES ('yy1', '3NF');
insert into NF (Tables,Form) VALUES ('yy1', 'BCNF');
select count(*) from (select distinct k1 from yy1) as AA;
select count(*) from yy1;
select count(*) from yy1 where k1 IS NULL;
select count(*) from (select A from yy1 group by A) as T1;
select count(*) from (select A,B from yy1 group by A,B) as T2;
select count(*) from (select A,C from yy1 group by A,C) as T2;
select count(*) from (select B from yy1 group by B) as T1;
select count(*) from (select B,A from yy1 group by B,A) as T2;
select count(*) from (select B,C from yy1 group by B,C) as T2;
select count(*) from (select C from yy1 group by C) as T1;
select count(*) from (select C,A from yy1 group by C,A) as T2;
select count(*) from (select C,B from yy1 group by C,B) as T2;
select count(*) from (select A, B from yy1 group by A, B) as T1;
select count(*) from (select A, B,C from yy1 group by A, B,C) as T2;
update NF set Y_N = 'N', Reason = 'A, B->C' WHERE Tables = 'yy1' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy1' and Form = 'BCNF';
insert into NF (Tables,Form) VALUES ('yy2', '3NF');
insert into NF (Tables,Form) VALUES ('yy2', 'BCNF');
select count(*) from (select distinct k1,k2 from yy2) as AA;
select count(*) from yy2;
select count(*) from yy2 where k1 IS NULL;
select count(*) from yy2 where k2 IS NULL;
insert into NF (Tables,Form) VALUES ('yy3', '3NF');
insert into NF (Tables,Form) VALUES ('yy3', 'BCNF');
select count(*) from (select distinct k1 from yy3) as AA;
select count(*) from yy3;
select count(*) from yy3 where k1 IS NULL;
select count(*) from (select A1 from yy3 group by A1) as T1;
select count(*) from (select A1,A2 from yy3 group by A1,A2) as T2;
update NF set Y_N = 'N', Reason = 'A1->A2' WHERE Tables = 'yy3' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy3' and Form = 'BCNF';
insert into NF (Tables,Form) VALUES ('yy4', '3NF');
insert into NF (Tables,Form) VALUES ('yy4', 'BCNF');
select count(*) from (select distinct A from yy4) as AA;
select count(*) from yy4;
select count(*) from yy4 where A IS NULL;
insert into NF (Tables,Form) VALUES ('yy5', '3NF');
insert into NF (Tables,Form) VALUES ('yy5', 'BCNF');
select count(*) from (select distinct P,Q from yy5) as AA;
select count(*) from yy5;
select count(*) from yy5 where P IS NULL;
select count(*) from yy5 where Q IS NULL;
select count(*) from (select P from yy5 group by P) as T1;
select count(*) from (select P,A from yy5 group by P,A) as T2;
update NF set Y_N = 'N', Reason = 'not 2nf, P->A' WHERE Tables = 'yy5' and Form = '3NF'
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy5' and Form = 'BCNF'
insert into NF (Tables,Form) VALUES ('yy6', '3NF');
insert into NF (Tables,Form) VALUES ('yy6', 'BCNF');
select count(*) from (select distinct k1,k2 from yy6) as AA;
select count(*) from yy6;
select count(*) from yy6 where k1 IS NULL;
select count(*) from yy6 where k2 IS NULL;
select count(*) from (select k1 from yy6 group by k1) as T1;
select count(*) from (select k1,A from yy6 group by k1,A) as T2;
select count(*) from (select k1,B from yy6 group by k1,B) as T2;
select count(*) from (select k2 from yy6 group by k2) as T1;
select count(*) from (select k2,A from yy6 group by k2,A) as T2;
select count(*) from (select k2,B from yy6 group by k2,B) as T2;
select count(*) from (select A from yy6 group by A) as T1;
select count(*) from (select A,B from yy6 group by A,B) as T2;
update NF set Y_N = 'N', Reason = 'A->B' WHERE Tables = 'yy6' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy6' and Form = 'BCNF';
insert into NF (Tables,Form) VALUES ('yy7', '3NF');
insert into NF (Tables,Form) VALUES ('yy7', 'BCNF');
select count(*) from (select distinct k1,k2 from yy7) as AA;
select count(*) from yy7;
select count(*) from yy7 where k1 IS NULL;
select count(*) from yy7 where k2 IS NULL;
select count(*) from (select k1 from yy7 group by k1) as T1;
select count(*) from (select k1,A1 from yy7 group by k1,A1) as T2;
select count(*) from (select k1,A2 from yy7 group by k1,A2) as T2;
select count(*) from (select k2 from yy7 group by k2) as T1;
select count(*) from (select k2,A1 from yy7 group by k2,A1) as T2;
select count(*) from (select k2,A2 from yy7 group by k2,A2) as T2;
select count(*) from (select A1 from yy7 group by A1) as T1;
select count(*) from (select A1,A2 from yy7 group by A1,A2) as T2;
select count(*) from (select A2 from yy7 group by A2) as T1;
select count(*) from (select A2,A1 from yy7 group by A2,A1) as T2;
update NF set Y_N = 'N', Reason = 'A2->A1' WHERE Tables = 'yy7' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy7' and Form = 'BCNF';
insert into NF (Tables,Form) VALUES ('yy8', '3NF');
insert into NF (Tables,Form) VALUES ('yy8', 'BCNF');
select count(*) from (select distinct A,B from yy8) as AA;
select count(*) from yy8;
select count(*) from yy8 where A IS NULL;
select count(*) from yy8 where B IS NULL;
select count(*) from (select A from yy8 group by A) as T1;
select count(*) from (select A,C from yy8 group by A,C) as T2;
select count(*) from (select A,D from yy8 group by A,D) as T2;
select count(*) from (select B from yy8 group by B) as T1;
select count(*) from (select B,C from yy8 group by B,C) as T2;
select count(*) from (select B,D from yy8 group by B,D) as T2;
select count(*) from (select C from yy8 group by C) as T1;
select count(*) from (select C,D from yy8 group by C,D) as T2;
update NF set Y_N = 'N', Reason = 'C->D' WHERE Tables = 'yy8' and Form = '3NF';
update NF set Y_N = 'N', Reason = 'not 3nf ' WHERE Tables = 'yy8' and Form = 'BCNF';
select * from NF;
select * from NF;
drop table NF
